#!/bin/bash
# ZORG-OMEGA: VOICE CREDENTIAL VAULT
# REPLACE THE VALUES BELOW WITH YOUR TWILIO DATA

export TWILIO_SID="YOUR_TWILIO_SID"
export TWILIO_TOKEN="YOUR_TWILIO_TOKEN"
export TWILIO_NUMBER="+1234567890"
